import type { KnowledgeChunk } from "../knowledge";

export const bioContactChunks: KnowledgeChunk[] = [
  {
    id: "bio-name",
    text: "Tyler Granlund is an IT Operations & Systems Engineer based in Bella Vista, Arkansas. He was formerly an IT Director.",
    topics: ["bio", "name", "location", "role", "title", "who"],
    source: "About",
    priority: 10,
  },
  {
    id: "bio-availability",
    text: "Tyler is currently looking for his next opportunity. He is available for full-time roles, consulting engagements, and collaborations. His last role was at Head to Toe Brands (Oct 2024 — Jan 2026). He is open to IT leadership, systems engineering, AI/ML engineering, forward-deployed engineering, and digital transformation roles. Based in Bella Vista, Arkansas. Remote-first, on-site travel as needed.",
    topics: [
      "hiring",
      "job",
      "role",
      "available",
      "open",
      "opportunity",
      "work",
      "employment",
      "status",
      "current",
    ],
    source: "About",
    priority: 10,
  },
  {
    id: "bio-philosophy",
    text: "Tyler's philosophy: support people, remove technological obstacles so their day-to-day is more fulfilling, create brand ambassadors by making work less stressful. Technology should serve people, not the other way around. The through-line across every role: understand what the customer needs, build the systems to support it, and remove the obstacles that make people's day-to-day harder.",
    topics: ["philosophy", "approach", "values", "people", "support", "mission"],
    source: "About",
    priority: 9,
  },
  {
    id: "bio-span",
    text: "Background spans franchise technology, B2B wholesale e-commerce, B2C brick-and-mortar e-commerce, agile product management, Microsoft cloud environments, data and BI modernization, and cross-functional transformation. Industries: beauty/franchise (Head to Toe Brands), wholesale/apparel (Outdoor Cap), music education/franchise (School of Rock), outdoor retail (North 40 / Smith & Rogue), consumer electronics (Apple).",
    topics: ["background", "experience", "domains", "industries", "span"],
    source: "About",
    priority: 8,
  },
  {
    id: "bio-beyond",
    text: "Beyond employment, Tyler builds enterprise dashboards, AI-powered tools, open-source agents, desktop applications, and accessible websites for local businesses. Side projects include Mysa Mail (local-first AI email agent), the TenantFleet ecosystem (7 open-source repos for multi-tenant governance), and the Spruce Grove Media creative studio.",
    topics: ["side projects", "open source", "ai", "agents", "tools", "personal"],
    source: "About",
    priority: 7,
  },
  {
    id: "contact-email",
    text: "You can reach Tyler directly at hello@tylergranlund.com. This is his primary contact for all inquiries about roles, collaborations, consulting, and general questions.",
    topics: ["contact", "email", "reach", "message", "hello", "inquiry"],
    source: "Contact",
    priority: 10,
  },
  {
    id: "contact-linkedin",
    text: "Tyler is on LinkedIn at linkedin.com/in/tylergranlund. This is a good place to connect for professional opportunities.",
    topics: ["linkedin", "social", "connect", "profile"],
    source: "Contact",
    priority: 8,
  },
  {
    id: "contact-github",
    text: "Tyler's GitHub is github.com/t-granlund. He publishes open-source work there, including the TenantFleet ecosystem repos.",
    topics: ["github", "code", "repos", "open source"],
    source: "Contact",
    priority: 7,
  },
  {
    id: "contact-location",
    text: "Tyler is based in Bella Vista, Arkansas (northwest Arkansas region, near Bentonville). He works remotely or on-site as needed. Willing to travel for the right opportunity.",
    topics: ["location", "remote", "bella vista", "arkansas", "travel"],
    source: "Contact",
    priority: 8,
  },
  {
    id: "contact-hiring",
    text: "Tyler is actively looking for his next opportunity. He has tailored resume variants for AI PM and FDE (Forward Deployed Engineer) positions, plus a master resume. Available for full-time, contract, consulting, and fractional engagements. Preferred contact: hello@tylergranlund.com.",
    topics: ["hiring", "job", "role", "consulting", "resume", "available", "open", "opportunity"],
    source: "Contact",
    priority: 10,
  },
  {
    id: "greeting-help",
    text: "Tyler is happy to answer questions about his work, background, skills, projects, or potential collaborations. For anything else, or to discuss a specific role, you can reach him at hello@tylergranlund.com.",
    topics: ["help", "hello", "hi", "hey", "what can you do", "who are you"],
    source: "Meta",
    priority: 10,
  },
  {
    id: "greeting-role",
    text: "Tyler is currently looking for his next opportunity. His last role was at Head to Toe Brands (Oct 2024 — Jan 2026). He is open to full-time roles, consulting, and collaborations in IT leadership, systems engineering, AI/ML engineering, or forward-deployed engineering. Contact: hello@tylergranlund.com.",
    topics: [
      "job",
      "hiring",
      "role",
      "position",
      "looking",
      "available",
      "open to work",
      "current",
    ],
    source: "Meta",
    priority: 10,
  },
  {
    id: "greeting-interview",
    text: "If you're a recruiter or hiring manager, Tyler has tailored resume variants for AI PM and FDE positions, plus a master resume. You can view and download them at tylergranlund.com/resume. His preferred contact is hello@tylergranlund.com. He is actively looking for his next opportunity.",
    topics: [
      "recruiter",
      "hiring manager",
      "interview",
      "resume",
      "cv",
      "opportunity",
      "available",
    ],
    source: "Meta",
    priority: 10,
  },
  {
    id: "greeting-what-can-you-do",
    text: "I can answer questions about Tyler's career history, technical skills, projects (Control Tower, Knowledge Fabric, Estate Trace, Mysa Mail, TenantFleet), work experience at Apple, School of Rock, Outdoor Cap, North 40, and Head to Toe Brands, his availability for roles, and how to contact him. If I don't have an answer, I'll direct you to hello@tylergranlund.com.",
    topics: ["what can you do", "capabilities", "help", "functions", "questions"],
    source: "Meta",
    priority: 10,
  },
  {
    id: "fallback-email",
    text: "I don't have a specific answer for that in my knowledge base, but Tyler would be glad to talk about it. Reach him directly at hello@tylergranlund.com or use the contact form on this site.",
    topics: ["fallback", "unknown", "dont know", "not sure", "no answer"],
    source: "Meta",
    priority: 10,
  },
];
