import type { KnowledgeChunk } from "../knowledge";

export const projectChunks: KnowledgeChunk[] = [
  {
    id: "project-ct",
    text: "Control Tower is a multi-tenant governance platform for cost, identity, and compliance across the whole estate. Built with Python/FastAPI + HTMX + PostgreSQL on the Azure SDK. Every release is gated by 7,386 automated tests and a 48/48 automated judge score. v2.5.0 is in production. All five tenants syncing live. Tyler chose server-rendered HTMX over a SPA to keep the attack surface small and auditable. It shipped to production; Tyler left before portfolio-wide rollout, and the architecture and guardrails are being open-sourced.",
    topics: [
      "control tower",
      "governance",
      "fastapi",
      "htmx",
      "postgresql",
      "azure",
      "testing",
      "judge",
    ],
    source: "Work",
    priority: 10,
  },
  {
    id: "project-ct-stack",
    text: "Control Tower tech stack: Python 3.12, FastAPI, Pydantic v2, SQLAlchemy, PostgreSQL 16, HTMX, Alpine.js, Tailwind CSS, Azure App Service, Azure Key Vault, Azure Storage. Deployed via GitHub Actions with OIDC authentication. 7,386 tests: pytest unit tests, Playwright E2E tests, accessibility tests with axe-core, and architecture fitness tests.",
    topics: [
      "control tower",
      "stack",
      "fastapi",
      "pydantic",
      "sqlalchemy",
      "htmx",
      "alpine",
      "tailwind",
    ],
    source: "Work",
    priority: 9,
  },
  {
    id: "project-kf",
    text: "Knowledge Fabric is an identity-aware RAG system that provides answers from 100K+ support tickets, scoped to who's asking. Built with a multi-agent ingestion pipeline using SQLite + FTS5 memory and Entra identity as the grounding layer. 1,523 verified humans across a 15-slot attribute schema. Phase 1 closed at 52/52 QA checks. Tyler left before portfolio-wide rollout; the identity-aware patterns are being open-sourced as part of TenantFleet.",
    topics: [
      "knowledge fabric",
      "rag",
      "sqlite",
      "fts5",
      "entra",
      "agents",
      "support",
      "ingestion",
    ],
    source: "Work",
    priority: 9,
  },
  {
    id: "project-kf-architecture",
    text: "Knowledge Fabric architecture: Multi-agent ingestion pipeline (extractor, transformer, embedder, indexer). SQLite with FTS5 for full-text search. Entra ID for identity grounding and access control. 15-slot attribute schema for user profiles. 100K+ support tickets indexed. Phase 1: 52/52 QA checks passed. Phase 2 (planned): enhanced retrieval with knowledge graph integration — left before portfolio-wide rollout.",
    topics: ["knowledge fabric", "architecture", "sqlite", "fts5", "entra", "pipeline", "indexer"],
    source: "Work",
    priority: 8,
  },
  {
    id: "project-et",
    text: "Estate Trace answers 'what do we run and what does it cost' across 41 repos, 11 subscriptions, and ~196 Azure resources. It uses live read-only pulls against version control, identity, cloud cost management, invoices, and licensing APIs feeding a DuckDB warehouse. 12/12 verification checks gate every refresh. It shipped to production to inform executive cost decisions; Tyler left before portfolio-wide rollout.",
    topics: [
      "estate trace",
      "cost",
      "duckdb",
      "azure",
      "finops",
      "executive",
      "resources",
      "repos",
    ],
    source: "Work",
    priority: 9,
  },
  {
    id: "project-et-data",
    text: "Estate Trace data sources: GitHub API for 41 repos, Azure Cost Management API for cloud spend, Azure Resource Manager for resource inventory, Microsoft Graph for licensing, invoice APIs for billing data. All feeds into a DuckDB analytical warehouse. 12/12 verification checks on every refresh ensure data integrity.",
    topics: [
      "estate trace",
      "data",
      "github api",
      "azure cost",
      "resource manager",
      "licensing",
      "duckdb",
    ],
    source: "Work",
    priority: 8,
  },
  {
    id: "project-zs",
    text: "Zero-secret automation provides full lifecycle automation (onboarding, offboarding, leave-of-absence) across five tenants without storing a single credential. Uses GitHub Actions with workload identity federation per tenant, driven from project management and CSV inputs. Every run leaves an audit trail with least-privilege permissions.",
    topics: [
      "zero secret",
      "oidc",
      "github actions",
      "federation",
      "lifecycle",
      "automation",
      "security",
    ],
    source: "Work",
    priority: 9,
  },
  {
    id: "project-zs-workflow",
    text: "Zero-secret workflow: Project management tool (Monday.com) triggers GitHub Actions via webhooks. GitHub Actions authenticates to Azure via OIDC workload identity federation (no stored secrets). Actions perform user lifecycle operations across 5 Entra ID tenants. Results logged to audit trail. CSV input files drive bulk operations. Onboarding: days to minutes. Offboarding: immediate and auditable.",
    topics: ["zero secret", "workflow", "oidc", "webhook", "monday", "lifecycle", "audit"],
    source: "Work",
    priority: 8,
  },
  {
    id: "project-mysa",
    text: "Mysa Mail is a local-first AI email agent that asks before it acts. Built with FastAPI + SvelteKit, 5,700+ LOC backend, 5 classifiers, and approval workflows before any destructive write. Uses local Ollama by default with cloud opt-in. WCAG 2.2 AA throughout. Shipped and in daily use.",
    topics: ["mysa mail", "email", "ollama", "sveltekit", "fastapi", "local", "ai", "personal"],
    source: "Work",
    priority: 7,
  },
  {
    id: "project-mysa-features",
    text: "Mysa Mail features: 5 email classifiers (urgent, follow-up, newsletter, social, spam). Approval workflow before any destructive action (delete, archive, reply). Local-first with Ollama (default) and cloud LLM opt-in. SvelteKit frontend with WCAG 2.2 AA accessibility. FastAPI backend with Pydantic models. SQLite for local data. 5,700+ lines of backend code.",
    topics: ["mysa mail", "features", "classifier", "approval", "ollama", "sveltekit", "sqlite"],
    source: "Work",
    priority: 7,
  },
  {
    id: "project-eco",
    text: "The TenantFleet Ecosystem is seven open-source repositories for multi-tenant Microsoft Entra ID governance. Built for MSPs, PE firms, and multi-brand portfolios. All MIT-licensed and deployable to GitHub Pages. The seven repos are: TenantFleet (root framework), HubForge (SWA templates), EntraGroups (group lifecycle), TenantForge (Terraform provisioning), DNSGuard (domain security), RampGuard (finance compliance), and SharePointAgent (document indexing).",
    topics: ["tenantfleet", "ecosystem", "open source", "mit", "entra id", "governance", "repos"],
    source: "Work/Ecosystem",
    priority: 9,
  },
  {
    id: "project-eco-repos",
    text: "TenantFleet Ecosystem repos: (1) TenantFleet — root governance framework for multi-tenant Entra ID. (2) HubForge — Static Web App templates for Azure deployment. (3) EntraGroups — Microsoft 365 group lifecycle management. (4) TenantForge — Terraform modules for tenant provisioning. (5) DNSGuard — Domain security monitoring and alerting. (6) RampGuard — Finance compliance and expense governance. (7) SharePointAgent — Document indexing and search. All MIT-licensed on GitHub.",
    topics: [
      "tenantfleet",
      "repos",
      "hubforge",
      "entragroups",
      "tenantforge",
      "dnsguard",
      "rampguard",
      "sharepointagent",
    ],
    source: "Work/Ecosystem",
    priority: 8,
  },
  {
    id: "venture-spruce",
    text: "Spruce Grove Media was a creative production studio Tyler founded and ran. He handled producing, post-editing, sound design, and color grading. In collaboration with Benton Drones, he produced first-person-view single-take films of local businesses and towns. He also cut weddings, events, and local shops — barbershops, craft stores, and more.",
    topics: ["spruce grove", "media", "video", "production", "fpv", "drone", "creative"],
    source: "Ventures",
    priority: 6,
  },
  {
    id: "venture-space-goose",
    text: "For Bentonville Brewing Company's 'Space Goose' release, Tyler wrote, animated, and scored a short cartoon film — a product release told as a cartoon. Just for the fun of it, but it shows how good creative doesn't always need a drone or a deadline.",
    topics: ["bentonville brewing", "space goose", "animation", "cartoon", "film", "creative"],
    source: "Ventures",
    priority: 6,
  },
  {
    id: "venture-zipline",
    text: "Benton Drones and Tyler were brought in with Zipline to capture survey data for the Walmart drone-delivery pilot. Tyler worked as a data-capture analyst, running rigs that recorded LiDAR, infrared, and high-resolution camera data, then validating datasets for Zipline's V2 delivery platform.",
    topics: ["zipline", "walmart", "drone", "lidar", "infrared", "data capture", "pilot"],
    source: "Ventures",
    priority: 7,
  },
  {
    id: "code-puppy",
    text: "Code Puppy is the supervised multi-agent system Tyler uses to build production software. It uses planner, programmer, code-reviewer, and security-auditor agents with human-in-the-loop approvals before any destructive write. Every release is gated by automated tests and judge scores. Tyler is a contributor to the open-source project.",
    topics: ["code puppy", "agent", "ai", "multi-agent", "award", "innovation", "how he builds"],
    source: "Work",
    priority: 9,
  },
  {
    id: "code-puppy-agents",
    text: "Code Puppy agent architecture: Planner agent breaks work into tasks. Programmer agent writes code. Code-reviewer agent checks quality, style, and correctness. Security-auditor agent checks for vulnerabilities and compliance. Human-in-the-loop approval gates before any destructive write (database changes, production deployments, credential operations). Automated test suite (7,386 tests) and judge score (48/48) gate every release.",
    topics: [
      "code puppy",
      "architecture",
      "planner",
      "programmer",
      "reviewer",
      "security",
      "human in loop",
    ],
    source: "Work",
    priority: 8,
  },
  {
    id: "resume-variants",
    text: "Tyler has three resume variants available for download at tylergranlund.com/resume: (1) Master Resume — comprehensive view of all experience. (2) AI PM Resume — tailored for AI Product Manager roles emphasizing agent systems, RAG, and evaluation. (3) FDE Resume — tailored for Forward Deployed Engineer roles emphasizing customer-facing technical work and rapid deployment.",
    topics: ["resume", "cv", "download", "pdf", "ai pm", "fde", "master"],
    source: "Meta",
    priority: 9,
  },
];
