import type { KnowledgeChunk } from "../knowledge";

export const skillsChunks: KnowledgeChunk[] = [
  // AI & Agents
  {
    id: "skills-ai-orchestration",
    text: "Multi-agent orchestration: Tyler builds systems with planner, programmer, code-reviewer, and security-auditor agents. Uses human-in-the-loop approvals before any destructive write. Every release is gated by automated tests and judge scores. He uses Code Puppy, an open-source multi-agent system, as his build environment.",
    topics: ["ai", "agents", "orchestration", "multi-agent", "code puppy", "how he builds"],
    source: "Skills",
    priority: 10,
  },
  {
    id: "skills-ai-rag",
    text: "RAG + knowledge graphs: Tyler built Knowledge Fabric, an identity-aware RAG system using SQLite + FTS5 memory and Entra identity as the grounding layer. It answers from 100K+ support tickets scoped to who's asking. 1,523 verified humans across a 15-slot attribute schema. Also works with knowledge graphs for structured data retrieval.",
    topics: ["rag", "retrieval", "knowledge", "fabric", "sqlite", "fts5", "entra"],
    source: "Skills",
    priority: 9,
  },
  {
    id: "skills-ai-evals",
    text: "Evaluation harnesses & judge gates: Tyler's systems use automated evaluation before production. Control Tower is gated by 7,386 automated tests and a 48/48 automated judge score. Every release must pass evals. He uses pytest, Vitest, and Playwright for different layers of testing.",
    topics: ["evaluation", "testing", "judge", "harness", "quality", "automated"],
    source: "Skills",
    priority: 9,
  },
  {
    id: "skills-ai-local",
    text: "Local-first LLMs: Tyler uses Ollama for running models locally. He built Mysa Mail with local Ollama by default and cloud opt-in. Works with Whisper for speech-to-text. Experience with prompt engineering for both local and cloud models. Prefers local-first architectures for privacy and cost.",
    topics: ["ollama", "local", "local-first", "llm", "whisper", "privacy", "cost"],
    source: "Skills",
    priority: 8,
  },
  {
    id: "skills-ai-tools",
    text: "Tool / function calling: Tyler builds agents that call external APIs and tools as part of their workflow. Uses structured output (Pydantic models) for type-safe tool responses. Experience with building tool registries and dynamic tool discovery.",
    topics: ["tools", "function calling", "api", "agents", "pydantic", "structured output"],
    source: "Skills",
    priority: 8,
  },
  // Languages
  {
    id: "skills-python",
    text: "Python: FastAPI for high-performance APIs, Pydantic for data validation and serialization, SQLAlchemy for ORM, pytest for testing. Built Control Tower (Python/FastAPI + HTMX + PostgreSQL). Experience with async Python, type hints, and packaging. Familiar with NumPy and pandas for data work.",
    topics: ["python", "fastapi", "pydantic", "sqlalchemy", "pytest", "async", "api"],
    source: "Skills",
    priority: 9,
  },
  {
    id: "skills-typescript",
    text: "TypeScript / Node.js: React (this portfolio site), SvelteKit (Mysa Mail), HTMX (Control Tower frontend). Experience with TanStack Router, TanStack Query, Vite, Vitest. Node.js for backend APIs and tooling. Strong typing discipline — uses strict TypeScript everywhere.",
    topics: ["typescript", "react", "sveltekit", "htmx", "node", "vite", "vitest", "frontend"],
    source: "Skills",
    priority: 9,
  },
  {
    id: "skills-sql",
    text: "SQL / DAX: Advanced SQL for complex queries, window functions, CTEs, and optimization. DAX for Power BI measures and calculated columns. Experience with stored procedures, indexing strategies, and query performance tuning across PostgreSQL, SQL Server, and DuckDB.",
    topics: ["sql", "dax", "database", "query", "performance", "postgresql", "sql server"],
    source: "Skills",
    priority: 8,
  },
  {
    id: "skills-powershell",
    text: "PowerShell / Bash: PowerShell for Windows automation, Active Directory scripts, Microsoft 365 administration, and Azure CLI workflows. Bash for Linux/macOS scripting, server management, CI/CD pipelines, and Docker operations. Comfortable with both.",
    topics: ["powershell", "bash", "scripting", "automation", "windows", "linux"],
    source: "Skills",
    priority: 7,
  },
  // Cloud & Identity
  {
    id: "skills-azure",
    text: "Azure: App Service for web hosting, Functions for serverless compute, Key Vault for secrets management, Storage for blob and queue operations, Entra ID for identity and access management. Experience with Azure SDK for Python, ARM templates, and Bicep for infrastructure-as-code. Cost governance and FinOps practices.",
    topics: ["azure", "app service", "functions", "key vault", "entra id", "bicep", "finops"],
    source: "Skills",
    priority: 9,
  },
  {
    id: "skills-aws",
    text: "AWS: Lambda for serverless functions, ECS Fargate for containerized workloads, Athena for SQL-on-S3 analytics, S3 for object storage. Experience with IAM policies, CloudWatch monitoring, and cost optimization. Less deep than Azure but production-capable.",
    topics: ["aws", "lambda", "ecs", "fargate", "athena", "s3", "iam", "cloudwatch"],
    source: "Skills",
    priority: 7,
  },
  {
    id: "skills-entra",
    text: "Entra ID multi-tenant: Built identity federation across 5+ Microsoft tenants. Role-based access control (RBAC) with custom roles. Conditional access policies. PIM for just-in-time admin access. Microsoft Graph API for programmatic user, group, and license management. Experience with B2B collaboration and cross-tenant access settings.",
    topics: [
      "entra id",
      "azure ad",
      "rbac",
      "conditional access",
      "pim",
      "microsoft graph",
      "multi-tenant",
    ],
    source: "Skills",
    priority: 9,
  },
  {
    id: "skills-oidc",
    text: "OIDC workload identity (zero secrets): Tyler's preferred authentication pattern. Uses GitHub Actions with workload identity federation per tenant — no stored credentials. Every automation run uses short-lived tokens with least-privilege permissions. This is the zero-secret automation approach he built at Head to Toe Brands.",
    topics: [
      "oidc",
      "federation",
      "zero secret",
      "github actions",
      "workload identity",
      "security",
    ],
    source: "Skills",
    priority: 9,
  },
  {
    id: "skills-terraform",
    text: "Bicep / Terraform: Infrastructure-as-code for Azure resources. Bicep for native Azure deployments. Terraform for multi-cloud and third-party provider management. State management, module design, and CI/CD integration for infrastructure changes.",
    topics: ["terraform", "bicep", "iac", "infrastructure", "deployment", "state"],
    source: "Skills",
    priority: 7,
  },
  // Data & BI
  {
    id: "skills-powerbi",
    text: "Power BI / Fabric (Direct Lake): Built executive dashboards and operational reports. Direct Lake mode for real-time data. Row-level security (RLS) for data segmentation by role/tenant. DAX measures and calculated tables. Integration with Azure Data Lake, SQL Server, and Snowflake. Experience with paginated reports and Power BI Embedded.",
    topics: ["power bi", "fabric", "direct lake", "rls", "dashboard", "executive", "dax"],
    source: "Skills",
    priority: 8,
  },
  {
    id: "skills-snowflake",
    text: "Snowflake: Cloud data warehouse for analytics workloads. Experience with SnowSQL, warehouse sizing, and cost optimization. Integration with Power BI and other BI tools. Familiar with Snowflake's RBAC and data sharing features.",
    topics: ["snowflake", "data warehouse", "analytics", "snowsql"],
    source: "Skills",
    priority: 7,
  },
  {
    id: "skills-postgres",
    text: "PostgreSQL: Primary database for Control Tower and other production systems. Experience with advanced indexing, partitioning, JSONB storage, full-text search, and performance tuning. Uses PostgreSQL as the backend for Knowledge Fabric's FTS5 alternative.",
    topics: ["postgresql", "postgres", "database", "jsonb", "full text search", "indexing"],
    source: "Skills",
    priority: 8,
  },
  {
    id: "skills-sqlserver",
    text: "SQL Server: Enterprise database management. Experience with Always On availability groups, query store for performance monitoring, and SQL Server Agent for job scheduling. Integration with Microsoft Dataverse and Dynamics 365.",
    topics: ["sql server", "database", "always on", "query store", "agent"],
    source: "Skills",
    priority: 6,
  },
  {
    id: "skills-duckdb",
    text: "DuckDB: In-process analytical database used for Estate Trace. Fast analytical queries on local/embedded data. Integration with Python for data analysis pipelines. Zero external dependencies, perfect for local-first data tools.",
    topics: ["duckdb", "analytical", "local", "python", "estate trace"],
    source: "Skills",
    priority: 7,
  },
  {
    id: "skills-etl",
    text: "ETL pipeline design: Extract-transform-load pipelines for data warehousing and analytics. Experience with Azure Data Factory, custom Python ETL scripts, and event-driven architectures. Focus on idempotent, retry-safe, and observable pipelines.",
    topics: ["etl", "pipeline", "data factory", "data", "analytics", "event driven"],
    source: "Skills",
    priority: 7,
  },
  // Quality & Delivery
  {
    id: "skills-cicd",
    text: "GitHub Actions CI/CD: Comprehensive CI/CD pipelines with automated testing, linting, type checking, security scanning, and deployment. Uses matrix builds, caching, artifact handling, and environment-based deployments. OIDC-based authentication to Azure and AWS. Experience with branch protection, required status checks, and merge queues.",
    topics: [
      "github actions",
      "ci/cd",
      "pipeline",
      "deployment",
      "automation",
      "branch protection",
    ],
    source: "Skills",
    priority: 9,
  },
  {
    id: "skills-playwright",
    text: "Playwright E2E: Full end-to-end test suites for web applications. Cross-browser testing (Chromium, Firefox, WebKit). Accessibility testing integration with axe-core. Page object model for maintainable tests. Visual regression testing. Performance testing with timing measurements.",
    topics: [
      "playwright",
      "e2e",
      "testing",
      "accessibility",
      "axe",
      "cross browser",
      "visual regression",
    ],
    source: "Skills",
    priority: 8,
  },
  {
    id: "skills-pytest",
    text: "pytest / Vitest: pytest for Python backend testing with fixtures, parametrization, and coverage. Vitest for TypeScript/JavaScript unit testing. Both with coverage reporting and integration into CI/CD gates. Aim for high test coverage on critical paths.",
    topics: ["pytest", "vitest", "unit testing", "coverage", "fixtures", "parametrization"],
    source: "Skills",
    priority: 8,
  },
  {
    id: "skills-a11y",
    text: "WCAG 2.2 AA (axe-core): Accessibility-first development. Uses axe-core for automated accessibility testing in CI. Semantic HTML, ARIA landmarks, skip links, focus management, keyboard operability, and screen reader testing. This portfolio site has zero axe violations.",
    topics: ["accessibility", "wcag", "a11y", "axe", "aria", "semantic html", "screen reader"],
    source: "Skills",
    priority: 9,
  },
  {
    id: "skills-security",
    text: "STRIDE threat modeling: Systematic security analysis. Identifies Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, and Elevation of Privilege threats. Integrates security review into the development lifecycle.",
    topics: [
      "security",
      "stride",
      "threat modeling",
      "spoofing",
      "tampering",
      "information disclosure",
    ],
    source: "Skills",
    priority: 8,
  },
  {
    id: "skills-finops",
    text: "FinOps / cost governance: Cloud cost optimization and governance. Built Estate Trace specifically to answer 'what do we run and what does it cost' across 41 repos, 11 subscriptions, and ~196 Azure resources. Tags, budgets, alerts, and right-sizing recommendations.",
    topics: ["finops", "cost", "governance", "cloud", "budget", "estate trace"],
    source: "Skills",
    priority: 8,
  },
  // Platform Integrations
  {
    id: "skills-freshdesk",
    text: "Freshdesk: Built and administered the support center at Head to Toe Brands. Ticket workflows, automation rules, SLA management, knowledge base, and agent productivity tools. Integrated with other systems for contextual support.",
    topics: ["freshdesk", "help desk", "support", "ticket", "sla", "automation"],
    source: "Skills",
    priority: 7,
  },
  {
    id: "skills-monday",
    text: "Monday.com: Project management and work OS. Used for sprint planning, task tracking, and cross-functional coordination. Experience with automations, integrations, and custom workflows.",
    topics: ["monday.com", "project management", "work os", "sprint", "planning"],
    source: "Skills",
    priority: 6,
  },
  {
    id: "skills-hubspot",
    text: "HubSpot: CRM and marketing automation. Contact management, deal pipelines, email sequences, and reporting. Integration with other business systems for unified customer data.",
    topics: ["hubspot", "crm", "marketing", "automation", "pipeline", "email"],
    source: "Skills",
    priority: 6,
  },
  {
    id: "skills-franconnect",
    text: "FranConnect: Franchise management platform. Used for franchisee onboarding, compliance tracking, and operational reporting. Integration with other IT systems for unified franchise data.",
    topics: ["franconnect", "franchise", "onboarding", "compliance", "reporting"],
    source: "Skills",
    priority: 6,
  },
  {
    id: "skills-mindbody",
    text: "Mindbody / Zenoti: Scheduling and booking platforms for service businesses. Used extensively at School of Rock and Head to Toe Brands. Integration with payment processing and CRM systems.",
    topics: ["mindbody", "zenoti", "scheduling", "booking", "salon", "spa"],
    source: "Skills",
    priority: 6,
  },
  {
    id: "skills-commerce",
    text: "BigCommerce / Shopify: E-commerce platforms for B2C retail. Experience with theme development, app integrations, payment gateways, and order management. Used at North 40 Outfitters.",
    topics: ["bigcommerce", "shopify", "e-commerce", "b2c", "retail", "theme", "payment"],
    source: "Skills",
    priority: 6,
  },
  {
    id: "skills-ramp",
    text: "Ramp: Corporate card and expense management. Integration with accounting systems for automated expense categorization and approval workflows.",
    topics: ["ramp", "expense", "corporate card", "finance", "accounting"],
    source: "Skills",
    priority: 5,
  },
  {
    id: "skills-github-enterprise",
    text: "GitHub Enterprise: Organization administration, repository management, team permissions, and security policies. Code review workflows, branch protection, and compliance reporting.",
    topics: [
      "github",
      "enterprise",
      "repository",
      "code review",
      "branch protection",
      "compliance",
    ],
    source: "Skills",
    priority: 7,
  },
];
