import { useEffect } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { z } from "zod";

import qrSvgRaw from "@/components/brand/card-qr.svg?raw";
import "@/components/brand/card.css";

/**
 * /brand/card — print-ready 2-sided business card (bc-04).
 *
 * Implements research/business-card-print/layout-spec.md. Captured to a
 * 2-page PDF by scripts/render-card.mjs (bc-05). Unlinked, noindexed, and
 * absent from the sitemap — this route exists for the print pipeline only.
 *
 * ?guides=1 overlays trim/safe-zone review lines (never used for final PDF).
 */

const cardSearchSchema = z.object({
  guides: z.coerce.number().optional(),
});

export const Route = createFileRoute("/brand/card")({
  validateSearch: cardSearchSchema,
  head: () => ({
    meta: [
      { title: "Business Card — Tyler Granlund" },
      { name: "robots", content: "noindex, nofollow" },
    ],
  }),
  component: BrandCardPage,
});

/** Favicon tree glyph, badge rect dropped (layout-spec §1.3, Q2). */
const TREE_PATH =
  "M24 7 L13.8 22.3 H18.9 L11.25 34.2 H20.6 V41 H27.4 V34.2 H36.75 L29.1 22.3 H34.2 Z";

function Guides() {
  return (
    <div className="card-guides" aria-hidden="true">
      <div className="card-guides-cross" />
      <div className="card-guides-cross card-guides-cross--h" />
    </div>
  );
}

function CardFront({ guides }: { guides: boolean }) {
  return (
    <div className="card-page card-page--front">
      <div className="card-atmosphere" aria-hidden="true" />
      <div className="card-face">
        {/* F2 — tree glyph */}
        <svg
          className="card-tree"
          viewBox="0 0 48 48"
          role="img"
          aria-label="Granlund Grove tree mark"
        >
          <path d={TREE_PATH} fill="currentColor" />
        </svg>

        {/* F3 — name */}
        <h1 className="card-name">Tyler Granlund</h1>

        {/* F4 — cedar rule */}
        <div className="card-rule" aria-hidden="true" />

        {/* F5 — title */}
        <p className="card-title">Technology Leader — Product, Platform &amp; AI</p>

        {/* F6/F7 — contact block */}
        <p className="card-contact">
          <a className="card-contact-primary" href="mailto:hello@tylergranlund.com">
            hello@tylergranlund.com
          </a>
          <span className="card-contact-secondary">
            tylergranlund.com
            <span className="card-dot"> · </span>
            linkedin.com/in/tylergranlund
          </span>
        </p>
      </div>
      {guides && <Guides />}
    </div>
  );
}

function CardBack({ guides }: { guides: boolean }) {
  return (
    <div className="card-page">
      <div className="card-face">
        {/* B1/B2 — spruce-deep panel + inverted QR (quiet zone baked into the SVG) */}
        <div className="card-qr-panel">
          <div
            className="card-qr"
            role="img"
            aria-label="QR code linking to tylergranlund.com"
            // Generated by scripts/card-qr.mjs — trusted local asset, modules
            // are currentColor so .card-qr styles them to var(--mist).
            dangerouslySetInnerHTML={{ __html: qrSvgRaw }}
          />
        </div>

        {/* B3/B4 — human fallback URL + location */}
        <p className="card-back-meta">
          <span className="card-back-url">tylergranlund.com</span>
          <span className="card-back-location">Bella Vista, AR</span>
        </p>
      </div>
      {guides && <Guides />}
    </div>
  );
}

function BrandCardPage() {
  const { guides } = Route.useSearch();
  const showGuides = guides === 1;

  // Scope the print-CSS override to this route (layout-spec §6.2): the global
  // @media print block forces white backgrounds for résumé printing; the card
  // must print dark. The class is removed on unmount so no other route leaks.
  useEffect(() => {
    const root = document.documentElement;
    root.classList.add("brand-card-print");
    return () => root.classList.remove("brand-card-print");
  }, []);

  return (
    <main id="main-content" className="brand-card-root" tabIndex={-1}>
      <CardFront guides={showGuides} />
      <CardBack guides={showGuides} />
    </main>
  );
}
