/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as VenturesRouteImport } from './routes/ventures'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ColophonRouteImport } from './routes/colophon'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing.index'
import { Route as WritingRunningItFor200LocationsWithAiAgentsRouteImport } from './routes/writing.running-it-for-200-locations-with-ai-agents'
import { Route as ApiContactRouteImport } from './routes/api/contact'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const VenturesRoute = VenturesRouteImport.update({
  id: '/ventures',
  path: '/ventures',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ColophonRoute = ColophonRouteImport.update({
  id: '/colophon',
  path: '/colophon',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingRunningItFor200LocationsWithAiAgentsRoute =
  WritingRunningItFor200LocationsWithAiAgentsRouteImport.update({
    id: '/writing/running-it-for-200-locations-with-ai-agents',
    path: '/writing/running-it-for-200-locations-with-ai-agents',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/colophon': typeof ColophonRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/privacy': typeof PrivacyRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ventures': typeof VenturesRoute
  '/work': typeof WorkRoute
  '/api/contact': typeof ApiContactRoute
  '/writing/running-it-for-200-locations-with-ai-agents': typeof WritingRunningItFor200LocationsWithAiAgentsRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/colophon': typeof ColophonRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/privacy': typeof PrivacyRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ventures': typeof VenturesRoute
  '/work': typeof WorkRoute
  '/api/contact': typeof ApiContactRoute
  '/writing/running-it-for-200-locations-with-ai-agents': typeof WritingRunningItFor200LocationsWithAiAgentsRoute
  '/writing': typeof WritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRoute
  '/colophon': typeof ColophonRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/privacy': typeof PrivacyRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ventures': typeof VenturesRoute
  '/work': typeof WorkRoute
  '/api/contact': typeof ApiContactRoute
  '/writing/running-it-for-200-locations-with-ai-agents': typeof WritingRunningItFor200LocationsWithAiAgentsRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/career'
    | '/colophon'
    | '/contact'
    | '/ecosystem'
    | '/privacy'
    | '/resume'
    | '/sitemap.xml'
    | '/ventures'
    | '/work'
    | '/api/contact'
    | '/writing/running-it-for-200-locations-with-ai-agents'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career'
    | '/colophon'
    | '/contact'
    | '/ecosystem'
    | '/privacy'
    | '/resume'
    | '/sitemap.xml'
    | '/ventures'
    | '/work'
    | '/api/contact'
    | '/writing/running-it-for-200-locations-with-ai-agents'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/career'
    | '/colophon'
    | '/contact'
    | '/ecosystem'
    | '/privacy'
    | '/resume'
    | '/sitemap.xml'
    | '/ventures'
    | '/work'
    | '/api/contact'
    | '/writing/running-it-for-200-locations-with-ai-agents'
    | '/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareerRoute: typeof CareerRoute
  ColophonRoute: typeof ColophonRoute
  ContactRoute: typeof ContactRoute
  EcosystemRoute: typeof EcosystemRoute
  PrivacyRoute: typeof PrivacyRoute
  ResumeRoute: typeof ResumeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VenturesRoute: typeof VenturesRoute
  WorkRoute: typeof WorkRoute
  ApiContactRoute: typeof ApiContactRoute
  WritingRunningItFor200LocationsWithAiAgentsRoute: typeof WritingRunningItFor200LocationsWithAiAgentsRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ventures': {
      id: '/ventures'
      path: '/ventures'
      fullPath: '/ventures'
      preLoaderRoute: typeof VenturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colophon': {
      id: '/colophon'
      path: '/colophon'
      fullPath: '/colophon'
      preLoaderRoute: typeof ColophonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/running-it-for-200-locations-with-ai-agents': {
      id: '/writing/running-it-for-200-locations-with-ai-agents'
      path: '/writing/running-it-for-200-locations-with-ai-agents'
      fullPath: '/writing/running-it-for-200-locations-with-ai-agents'
      preLoaderRoute: typeof WritingRunningItFor200LocationsWithAiAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareerRoute: CareerRoute,
  ColophonRoute: ColophonRoute,
  ContactRoute: ContactRoute,
  EcosystemRoute: EcosystemRoute,
  PrivacyRoute: PrivacyRoute,
  ResumeRoute: ResumeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VenturesRoute: VenturesRoute,
  WorkRoute: WorkRoute,
  ApiContactRoute: ApiContactRoute,
  WritingRunningItFor200LocationsWithAiAgentsRoute:
    WritingRunningItFor200LocationsWithAiAgentsRoute,
  WritingIndexRoute: WritingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
